#%RAML 1.0
title: MyAccount
description: This is an API functional domain for my accounts
version: v1
baseUri: http://api.open-api-training.com/
protocols: [  HTTPS ]
mediaType: [ application/json ]

types:

  MyAccount:
    type: object
    properties:
      username: string
      avatar_url: string
      personal_info: PersonalInfo

  PersonalInfo:
    type: object
    properties:
      name: string
      surname: string
      cell: string
      e_mail: string

  MySession:
    type: object
    properties:
      _id: string
      username: string
      password: string
      access_token: string
      access_type: string
      access_type_details: string
      location_ip: string
      location_name: string
      date_time: datetime

/my-account:
  get:
    responses:
      200:
        headers:
          Content-Location:
        body:
          application/json:
            type: MyAccount

      400:
        description: Bad Request

      401:
        description: Unauthorized

      500:
        description: Server Error

  /sessions:
    get:
      responses:
        200:
          headers:
            Content-Location:
          body:
            application/json:
              type: MySession[]

        400:
          description: Bad Request

        401:
          description: Unauthorized

        500:
          description: Server Error
    post:
      body:
        application/json:
          type: MySession
      responses:
        201:
          body:
            application/json:
              type: MySession

        400:
          description: Bad Request

        401:
          description: Unauthorized

        500:
          description: Server Error
