#%RAML 1.0 DataType
properties:
  id: string
  account_number: string
  alias: string
  account_balance: string
  alerts: string
  status:
    type: string
    enum: [ "active", "blocked-by-legal", "inactive" ]
