#%RAML 1.0 Library
types:
  accountTransaction:
    type: object
    properties:
      id: string
      subject: string
      amount: number
      balance: number
      type:
        type: string
        enum: [ "ATM", "Charge", "Check", "Deposit", "Online", "POS", "Transfer", "Withdrawal" ]
